### ISSUE TITLE
Manage the cookies

### ISSUE THREAD

**Issue by oovm** [wjxway/ZhihuLink-Mathematica#17]
昨天的内测表明现在的操作很糟糕, 太过复杂, 绝大多数用户难以忍受这么多的步骤.

同时 #2  遇到了巨大的难题, 手动的添加 cookies 仍然是唯一的解决方案.

- [x] 需要一个cookies管理方案

**Comment by oovm** [comment]
Cookies 等同于账号与密码, 所以 Cookies 必定不能明文储存.

可以以二进制的方式储存在本地, 同时告知用户千万不要把自己的 Cookies 乱传

**Comment by oovm** [comment]
当ZhihuLink被激活时, 自动检查是否有可用的 Cookies

https://github.com/wjxway/ZhihuLink-Mathematica/blob/3b36bce78a28b75e6e1c2068077ebeda40d19aa1/Packages/__Raw/ZhihuLinkInit.wl#L41-L46

没有的话跳个提示, 搞个框, 手动激活

https://github.com/wjxway/ZhihuLink-Mathematica/blob/3b36bce78a28b75e6e1c2068077ebeda40d19aa1/Packages/__Raw/ZhihuLinkInit.wl#L47-L53

**Comment by oovm** [comment]
@wjxway 

创建 `ApplicationData/ZhihuLink/Settings.wxf`

数据本身以 Association 的形式存在即可, 用 BinarySerialize 编码为二进制加密, 

用 BinaryWrite 写入文件, Close 停止写入

**Comment by wjxway** [comment]
嗯，一点建议，就是可以在.m里面定义一些Private的东西，例如$ZhihuLinkStorageDirectory这样的，会方便很多。按这个思想我写的存cookie的代码大概这样：

```
$ZhihuLinkCookieFile = 
  FileNameJoin[{$ZhihuLinkStorageDirectory, "cookie_storage"}];

ExportCookie[
  asso_Association] := (If[FileExistsQ@$ZhihuLinkCookieFile, 
    DeleteFile[$ZhihuLinkCookieFile]] \
BinaryWrite[$ZhihuLinkCookieFile, 
    Encrypt[GenerateSymmetricKey[
       Uncompress@
        "1:eJxTTMoPClZmYGAIycgsVgCikoxUhezUSoW0/CKF5Pz87MxUheKS/\
KLE9FRFACiWDlA=", Method -> "RC4"], BinarySerialize@asso]["Data"]]; 
  Close[$ZhihuLinkCookieFile];)

ImportCookie[] := 
 BinaryDeserialize@
  Decrypt[GenerateSymmetricKey[
    Uncompress@
     "1:eJxTTMoPClZmYGAIycgsVgCikoxUhezUSoW0/CKF5Pz87MxUheKS/\
KLE9FRFACiWDlA=", Method -> "RC4"], 
   ByteArray@BinaryReadList@$ZhihuLinkCookieFile]
```

**Comment by wjxway** [comment]
这三个函数我觉得都该是Private的内容。还有，发现了个很神奇的事情，Firefox的cookie是直接可以读文件读出来的，但是是这么些项目：
![image](https://user-images.githubusercontent.com/34795160/37568109-8dee67d8-2b0b-11e8-91ce-af32716db442.png)
没有aliyun_tc这一项，然而照样可以登录知乎，很奇怪诶。
你们看看这个咋样？假如光这些信息够了我就可以做自动登录了~
